---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: gitlab
  {{- include "gitlab.labels" . | nindent 4 }}
  annotations:
  {{- include "gitlab.annotations" . | nindent 4 }}
  name: gitlab-prom
rules:
  - apiGroups:
      - ""
    resources:
      - "nodes"
      - "pods"
    verbs:
      - list
      - watch