{{- if .Values.namespace.create -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace.name}}
  labels:
  {{- include "gitlab.labels" . | nindent 4 }}
  annotations:
  {{- include "gitlab.annotations" . | nindent 4 }}
{{- end}}