---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: {{ .Values.namespace.name }}
  labels:
    app: gitlab
    tier: database
  {{- include "gitlab.labels" . | nindent 4 }}
  annotations:
  {{- include "gitlab.annotations" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.config.postgres.database.db }}
  POSTGRES_USER: {{ .Values.config.postgres.database.user }}
  POSTGRES_PASSWORD: {{ .Values.config.postgres.database.passwd }}
