---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gitlab
  {{- include "gitlab.labels" . | nindent 4 }}
  annotations:
  {{- include "gitlab.annotations" . | nindent 4 }}
  name: gitlab
  namespace: {{.Values.namespace.name}}