image:
  repo: docker.io/istio
  tag: 1.7.4
#  tag: 1.5.4
operator:
  name: istio-operator
  imagePullPolicy: IfNotPresent
  operatorNamespace:
    name: istio-operator
  prometheusNamespace:
    name: monitoring
  istioNamespace:
    name: istio-system
    create: true
  replicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  imagePullSecrets: { }
  podSecurityContext: { }
  nodeSelector: { }
  affinity: { }
  tolerations: { }
controlPlane:
  enabled: true
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        namespace: istio-system
#       k8s:
#          serviceAnnotations:
#            external-dns.alpha.kubernetes.io/hostname: some.domain.com
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        namespace: istio-system
#      k8s:
#        serviceAnnotations:
#          external-dns.alpha.kubernetes.io/hostname: some.domain.com

serviceMonitors:
  enabled: true  # Can be set to false to disable servicemonitor deployment
  labels: { }

  addonComponents:
    grafana:
      enabled: false
