---
# Default values for istio-operator.

image:
  repo: docker.io/istio
  tag: 1.7.4
#  tag: 1.5.4
operator:
  name: istio-operator
  imagePullPolicy: IfNotPresent
  operatorNamespace:
    name: istio-operator
  prometheusNamespace:
    name: monitoring
  istioNamespace:
    name: istio-system
    create: true
  replicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  imagePullSecrets: {}
  podSecurityContext: {}
  nodeSelector: {}
  affinity: {}
  tolerations: {}
controlPlane:
  enabled: true
  addonComponents:
    grafana:
      enabled: false
  meshConfig:
    accessLogFile: /dev/stdout
    enableAutoMtls: true
    outboundTrafficPolicy:
#      mode: REGISTRY_ONLY # TODO: You can enable this once infra is in place to manage it.
      mode: ALLOW_ANY
    rootNamespace: istio-system
    enablePrometheusMerge: true
    enableTracing: true
    defaultConfig:
      zipkin:
        address: PATH_TO_JAEGER
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        namespace: istio-system
    #         k8s:
    #           serviceAnnotations:
    #             external-dns.alpha.kubernetes.io/hostname: some.domain.com
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        namespace: istio-system
#         k8s:
#           serviceAnnotations:
#             external-dns.alpha.kubernetes.io/hostname: some.domain.com
serviceMonitors:
  enabled: true  # Can be set to false to disable servicemonitor deployment
  labels: {}

# Enable or disable Grafana Dashboard Loads
dashboards:
  enabled: true
