{{- if .Values.namespace.create -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace.name}}
  labels:
  {{- include "cert-manager.labels" . | nindent 4 }}
  annotations:
  {{- include "cert-manager.annotations" . | nindent 4 }}

{{- end}}