---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: cainjector
  {{- include "cert-manager.labels" . | nindent 4 }}
  annotations:
  {{- include "cert-manager.annotations" . | nindent 4 }}
  name: cert-manager-cainjector:leaderelection
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resourceNames:
      - cert-manager-cainjector-leader-election
      - cert-manager-cainjector-leader-election-core
    resources:
      - configmaps
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: cert-manager
  {{- include "cert-manager.labels" . | nindent 4 }}
  annotations:
  {{- include "cert-manager.annotations" . | nindent 4 }}
  name: cert-manager:leaderelection
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resourceNames:
      - cert-manager-controller
    resources:
      - configmaps
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: webhook
  {{- include "cert-manager.labels" . | nindent 4 }}
  annotations:
  {{- include "cert-manager.annotations" . | nindent 4 }}
  name: cert-manager-webhook:dynamic-serving
  namespace: {{.Values.namespace.name}}
rules:
  - apiGroups:
      - ""
    resourceNames:
      - cert-manager-webhook-ca
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create