---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: cert-manager
  {{- include "cert-manager.labels" . | nindent 4 }}
  annotations:
  {{- include "cert-manager.annotations" . | nindent 4 }}
  name: cert-manager
  namespace: {{.Values.namespace.name}}
spec:
  ports:
    - port: 9402
      protocol: TCP
      targetPort: 9402
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: cert-manager
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: webhook
  {{- include "cert-manager.labels" . | nindent 4 }}
  annotations:
  {{- include "cert-manager.annotations" . | nindent 4 }}
  name: cert-manager-webhook
  namespace: {{.Values.namespace.name}}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 10250
  selector:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: webhook
  type: ClusterIP