---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: cainjector
  {{- include "cert-manager.labels" . | nindent 4 }}
  annotations:
  {{- include "cert-manager.annotations" . | nindent 4 }}
  name: cert-manager-cainjector
  namespace: {{.Values.namespace.name}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: cert-manager
  {{- include "cert-manager.labels" . | nindent 4 }}
  annotations:
  {{- include "cert-manager.annotations" . | nindent 4 }}
  name: cert-manager
  namespace: {{.Values.namespace.name}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: webhook
  {{- include "cert-manager.labels" . | nindent 4 }}
  annotations:
  {{- include "cert-manager.annotations" . | nindent 4 }}
  name: cert-manager-webhook
  namespace: {{.Values.namespace.name}}