{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace.name}}
  labels:
  {{- include "metallb.labels" . | nindent 4 }}
  annotations:
  {{- include "metallb.annotations" . | nindent 4 }}
---
  {{- end}}