
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  {{- include "metallb.labels" . | nindent 4 }}
  annotations:
  {{- include "metallb.annotations" . | nindent 4 }}
  name: config-watcher
  namespace: {{ .Values.namespace.name }}
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  {{- include "metallb.labels" . | nindent 4 }}
  annotations:
  {{- include "metallb.annotations" . | nindent 4 }}
  name: pod-lister
  namespace: {{ .Values.namespace.name }}
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list