---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  {{- include "metallb.labels" . | nindent 4 }}
  annotations:
  {{- include "metallb.annotations" . | nindent 4 }}
  name: controller
  namespace: {{.Values.namespace.name}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  {{- include "metallb.labels" . | nindent 4 }}
  annotations:
  {{- include "metallb.annotations" . | nindent 4 }}
  name: speaker
  namespace: {{.Values.namespace.name}}